apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: project
  name: mongo
spec:
  serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo-container
          image: mongo
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
          resources:
            requests:
              memory: 200Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: requests-claim
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: requests-claim
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi