apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      namespace: logppa
      labels:
        app: log-output
    spec:
      containers:
        - name: writer-ts
          image: matibrax/writer-ts:4
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/src/app/files
        - name: reader-ts
          image: matibrax/rts:2.63
          volumeMounts: 
          - name: shared-logs
            mountPath: /usr/src/app/files
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: message-config
                key: MESSAGE
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: port-config
                key: PORT
      volumes: 
        - name: shared-logs
          persistentVolumeClaim:
            claimName: requests-claim


