apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-logs
          persistentVolumeClaim:
            claimName: requests-claim
      containers:
        - name: writer-ts
          image: matibrax/writer-ts:4
          volumeMounts: # Mount volume
          - name: shared-logs
            mountPath: /usr/src/app/files
        - name: reader-ts
          image: matibrax/rts:2.1
          volumeMounts: # Mount volume
          - name: shared-logs
            mountPath: /usr/src/app/files
