apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: requests-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi