apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: logppa
  name: ppa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppa
  template:
    metadata:
      labels:
        app: ppa
    spec:
      containers:
        - name: ppa-service
          image: matibrax/ppa:2.4