apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppa
  template:
    metadata:
      labels:
        app: ppa
    spec:
      volumes: # Define volume
        - name: shared-logs
          persistentVolumeClaim:
            claimName: requests-claim
      containers:
        - name: ppa
          image: matibrax/ppa:4
          volumeMounts: # Mount volume
          - name: shared-logs
            mountPath: /usr/src/app/files
