apiVersion: v1
kind: Secret
metadata:
    namespace: logppa
    name: ppa-apikey
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:y4cg5BTOkG+OWWRI4RIijA/CBJ3nZozhpxRZGykyBHLhCg2SJ10hWTflC/HawCfEKiAn7zfpktw=,iv:lVn7eFUd4kluD22dzUVbo0zOoaH1mAsaY+OqNutynFc=,tag:P4HfrgHISokBS9pImlvKrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g2y3j22xzmjgjy5yz96j63snp8hz3q4799cwfv0ps59zsu86jveq7ezy9x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSG13ZG10OHhmeSs5ak4x
            Zmw2djVtdGVSVkVXeDJ2aEN6ajZlWUsvSGdnCnFDcGVqdVpuQUs1cWhJSEtqdGpL
            QlVlbzY0TzI2SU1MZUVEbzllQXdDTk0KLS0tICtWVlpLNlFoVFhkZlJXQ2N4QUtn
            OEh2ZU03NHZFZkFJWUgyWGxWbDg3K2sKVtX7ZNHTm4MoU7Dz0AakmIST6CgBKGvv
            F0zofivdj8C1MZXEpwG/3prRlPDSyzxx0iu5Ddp8hFq5ADpv4Lse/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-22T11:12:49Z"
    mac: ENC[AES256_GCM,data:n5rTP58hU0shO9KI2F59W6cNAwp9ZRUooR1fvqMHmq6yz8LA5lnnEY9T3DVpY+2UNjOVdhvA1iyI/5NdRM7dXSIH7xkV5KrYxWeBBw4XTRHHCYt9wyhNqzvqilAkrOO4lijmNbXju8bKFPvZ6q0L5ZrrM/Ep1icOShiWWIDEG9Y=,iv:ELvmzcj3gFK5TeIHie1z23d7JrFSJ4dId44rnGy4waM=,tag:8V9fEpMegJ6l+K4BJOpNeA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
