apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todos-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-backend
  template:
    metadata:
      labels:
        app: todos-backend
    spec:
      containers:
        - name: todos-backend
          image: matibrax/pb:2.9
          env:
          - name: API
            valueFrom:
              configMapKeyRef:
                name: mongodb-config
                key: API