apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: mycron-container
spec:
    schedule: "0 0 * * *"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - name: mycron-container
              image: matibrax/todoshell:1
              imagePullPolicy: IfNotPresent
            restartPolicy: OnFailure